import {
    FaBuilding, FaHome, FaRoad, FaTree, FaWater, FaShieldAlt,
    FaFireExtinguisher, FaUtensils, FaTag
  } from 'react-icons/fa';
  
  const agencies = [
    // Ministries
    { id: 'PMO', name: "Prime Minister's Office", group: 'Ministry', icon: <FaBuilding /> },
    { id: 'MDDI', name: 'Ministry of Digital Development & Information', group: 'Ministry', icon: <FaBuilding /> },
    { id: 'MCCY', name: 'Ministry of Culture, Community & Youth', group: 'Ministry', icon: <FaBuilding /> },
    { id: 'MINDEF', name: 'Ministry of Defence', group: 'Ministry', icon: <FaShieldAlt /> },
    { id: 'MOE', name: 'Ministry of Education', group: 'Ministry', icon: <FaBuilding /> },
    { id: 'MOF', name: 'Ministry of Finance', group: 'Ministry', icon: <FaBuilding /> },
    { id: 'MFA', name: 'Ministry of Foreign Affairs', group: 'Ministry', icon: <FaBuilding /> },
    { id: 'MOH', name: 'Ministry of Health', group: 'Ministry', icon: <FaBuilding /> },
    { id: 'MHA', name: 'Ministry of Home Affairs', group: 'Ministry', icon: <FaShieldAlt /> },
    { id: 'MINLAW', name: 'Ministry of Law', group: 'Ministry', icon: <FaBuilding /> },
    { id: 'MOM', name: 'Ministry of Manpower', group: 'Ministry', icon: <FaBuilding /> },
    { id: 'MND', name: 'Ministry of National Development', group: 'Ministry', icon: <FaBuilding /> },
    { id: 'MSF', name: 'Ministry of Social & Family Development', group: 'Ministry', icon: <FaBuilding /> },
    { id: 'MSE', name: 'Ministry of Sustainability & the Environment', group: 'Ministry', icon: <FaTree /> },
    { id: 'MTI', name: 'Ministry of Trade & Industry', group: 'Ministry', icon: <FaBuilding /> },
    { id: 'MOT', name: 'Ministry of Transport', group: 'Ministry', icon: <FaRoad /> },
  
    // Statutory Boards & Autonomous Agencies
    { id: 'HDB', name: 'Housing & Development Board', group: 'Agency', icon: <FaHome /> },
    { id: 'URA', name: 'Urban Redevelopment Authority', group: 'Agency', icon: <FaBuilding /> },
    { id: 'CPF', name: 'Central Provident Fund Board', group: 'Agency', icon: <FaTag /> },
    { id: 'ACRA', name: 'Accounting & Corporate Regulatory Authority', group: 'Agency', icon: <FaBuilding /> },
    { id: 'A*STAR', name: 'Agency for Science, Technology & Research', group: 'Agency', icon: <FaBuilding /> },
    { id: 'CAAS', name: 'Civil Aviation Authority of Singapore', group: 'Agency', icon: <FaBuilding /> },
    { id: 'BCA', name: 'Building & Construction Authority', group: 'Agency', icon: <FaBuilding /> },
    { id: 'EDB', name: 'Economic Development Board', group: 'Agency', icon: <FaBuilding /> },
    { id: 'EnterpriseSG', name: 'Enterprise Singapore', group: 'Agency', icon: <FaBuilding /> },
    { id: 'EMA', name: 'Energy Market Authority', group: 'Agency', icon: <FaBuilding /> },
    { id: 'IMDA', name: 'Infocomm Media Development Authority', group: 'Agency', icon: <FaBuilding /> },
    { id: 'IRAS', name: 'Inland Revenue Authority of Singapore', group: 'Agency', icon: <FaBuilding /> },
    { id: 'LTA', name: 'Land Transport Authority', group: 'Agency', icon: <FaRoad /> },
    { id: 'MPA', name: 'Maritime & Port Authority of Singapore', group: 'Agency', icon: <FaBuilding /> },
    { id: 'MAS', name: 'Monetary Authority of Singapore', group: 'Agency', icon: <FaBuilding /> },
    { id: 'NEA', name: 'National Environment Agency', group: 'Agency', icon: <FaTag /> },
    { id: 'NHB', name: 'National Heritage Board', group: 'Agency', icon: <FaBuilding /> },
    { id: 'NLB', name: 'National Library Board', group: 'Agency', icon: <FaBuilding /> },
    { id: 'NParks', name: 'National Parks Board', group: 'Agency', icon: <FaTree /> },
    { id: 'PA', name: "People's Association", group: 'Agency', icon: <FaBuilding /> },
    { id: 'PUB', name: 'Public Utilities Board', group: 'Agency', icon: <FaWater /> },
    { id: 'STB', name: 'Singapore Tourism Board', group: 'Agency', icon: <FaBuilding /> },
    { id: 'SSG', name: 'SkillsFuture Singapore', group: 'Agency', icon: <FaBuilding /> },
    { id: 'WSG', name: 'Workforce Singapore', group: 'Agency', icon: <FaBuilding /> },
    { id: 'CEA', name: 'Council for Estate Agencies', group: 'Agency', icon: <FaBuilding /> },
    { id: 'CCCS', name: 'Competition & Consumer Commission of Singapore', group: 'Agency', icon: <FaBuilding /> },
    { id: 'DSTA', name: 'Defence Science & Technology Agency', group: 'Agency', icon: <FaShieldAlt /> },
    { id: 'HTX', name: 'Home Team Science & Technology Agency', group: 'Agency', icon: <FaShieldAlt /> },
    { id: 'HLB', name: 'Hotels Licensing Board', group: 'Agency', icon: <FaBuilding /> },
    { id: 'ITE', name: 'Institute of Technical Education', group: 'Agency', icon: <FaBuilding /> },
    { id: 'IPOS', name: 'Intellectual Property Office of Singapore', group: 'Agency', icon: <FaBuilding /> },
    { id: 'ISEAS', name: 'ISEAS–Yusof Ishak Institute', group: 'Agency', icon: <FaBuilding /> },
    { id: 'JTC', name: 'JTC Corporation', group: 'Agency', icon: <FaBuilding /> },
    { id: 'LSB', name: 'Land Surveyors Board', group: 'Agency', icon: <FaBuilding /> },
    { id: 'MUIS', name: 'Majlis Ugama Islam Singapura', group: 'Agency', icon: <FaBuilding /> },
    { id: 'NAC', name: 'National Arts Council', group: 'Agency', icon: <FaBuilding /> },
    { id: 'NCSS', name: 'National Council of Social Service', group: 'Agency', icon: <FaBuilding /> },
    { id: 'RP', name: 'Republic Polytechnic', group: 'Agency', icon: <FaBuilding /> },
    { id: 'SCB', name: 'Science Centre Board', group: 'Agency', icon: <FaBuilding /> },
    { id: 'SDC', name: 'Sentosa Development Corporation', group: 'Agency', icon: <FaBuilding /> },
    { id: 'SPF', name: 'Singapore Police Force', group: 'Agency', icon: <FaShieldAlt /> },
    { id: 'SCDF', name: 'Singapore Civil Defence Force', group: 'Agency', icon: <FaFireExtinguisher /> },
    { id: 'SFA', name: 'Singapore Food Agency', group: 'Agency', icon: <FaUtensils /> },
    { id: 'SLA', name: 'Singapore Land Authority', group: 'Agency', icon: <FaBuilding /> },
    { id: 'SMC', name: 'Singapore Medical Council', group: 'Agency', icon: <FaBuilding /> },
    { id: 'SNB', name: 'Singapore Nursing Board', group: 'Agency', icon: <FaBuilding /> },
    { id: 'SP', name: 'Singapore Polytechnic', group: 'Agency', icon: <FaBuilding /> },
    { id: 'SEAB', name: 'Singapore Examinations & Assessment Board', group: 'Agency', icon: <FaBuilding /> },
    { id: 'SLF', name: 'Singapore Labour Foundation', group: 'Agency', icon: <FaBuilding /> },
    { id: 'SPC', name: 'Singapore Pharmacy Council', group: 'Agency', icon: <FaBuilding /> },
    { id: 'ToteBoard', name: 'Tote Board', group: 'Agency', icon: <FaBuilding /> },
    { id: 'YRSG', name: 'Yellow Ribbon Singapore', group: 'Agency', icon: <FaBuilding /> },
  ];
  
  export default agencies;  
